<div style="display: flex; background-color: RGB(255,114,0);" >
<h1 style="margin: auto; padding: 30px; ">ANALYSE DE FICHIERS POUR PREPARER UNE ETUDE DE MARCHE</h1>
</div>


L'objectif est de constituer un dataframe prêt à être utiliser pour réaliser un clustering et une ACP permettant à l'entreprise *La Poule qui chante* de determiner dans quel pays  elle peut envisager de se developper.

#### **Ce notebook se divise en 4 étapes :**

**-1 Importation des librairies et des différents fichiers csv**

**-2 Analyse exploratoire des différents dataframe**

**-3 Agrégation des dataframes en un dataframe unique**

**-4 Standardisation des données et extraction du fichier final**


<div style="background-color: RGB(51,165,182);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 1 - Importation des librairies et chargement des fichiers</h2>
</div>

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">1.1 - Importation des librairies</h3>
</div>

In [5]:
#Importation de la librairie Pandas
import pandas as pd
#Importation de la librairie numpy
import numpy as np

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">1.2 - Chargement des fichiers</h3>
</div>

In [7]:
#Importation du fichier DisponibiliteAlimentaire_2017.csv
df_dispo_alimentaire_2017 = pd.read_csv("DisponibiliteAlimentaire_2017.csv")
#Importation du fichier Population_2000_2018.csv
df_population = pd.read_csv("Population_2000_2018.csv")
#Importation du fichier du %_pop_urbaine_2017
df_pop_urbaine_2017 = pd.read_csv("%_pop_urbaine_2017.csv")
#Importation du fichier croissance_PIB_2017
df_croissance_pib_2017 = pd.read_csv("croissance_PIB_2017.csv")
#Importation du fichier doing_business_2017
df_doing_business_2017 = pd.read_csv("doing_business_2017.csv")
#Importation du fichier IDH_2017
df_idh_2017 = pd.read_csv("IDH_2017.csv", sep=';')
#Importation du fichier pib_par_habitants_2017
df_pib_hbt_2017 = pd.read_csv("pib_par_habitants_2017.csv")
#Importation du fichier stabilité_politique_2017
df_stabilité_politique_2017 = pd.read_csv("stabilité_politique_2017.csv")
#Importation du fichier liaison_zone_fr_en
df_liaison_zone = pd.read_csv("liaison_zone_fr_en.csv")

<div style="background-color: RGB(51,165,182);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 2 - Analyse exploratoire des fichiers</h2>
</div>

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">2.1 - Analyse exploratoire du dataframe df_dispo_alimentaire_2017</h3>
</div>

In [10]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(df_dispo_alimentaire_2017.shape[0]))
print("Le tableau comporte {} colonne(s)".format(df_dispo_alimentaire_2017.shape[1]))

Le tableau comporte 176600 observation(s) ou article(s)
Le tableau comporte 14 colonne(s)


In [11]:
#Consulter le nombre de colonnes , La nature des données dans chacune des colonnes, et le nombre de valeurs présentes dans chacune des colonnes
df_dispo_alimentaire_2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176600 entries, 0 to 176599
Data columns (total 14 columns):
 #   Column                  Non-Null Count   Dtype  
---  ------                  --------------   -----  
 0   Code Domaine            176600 non-null  object 
 1   Domaine                 176600 non-null  object 
 2   Code zone               176600 non-null  int64  
 3   Zone                    176600 non-null  object 
 4   Code Élément            176600 non-null  int64  
 5   Élément                 176600 non-null  object 
 6   Code Produit            176600 non-null  int64  
 7   Produit                 176600 non-null  object 
 8   Code année              176600 non-null  int64  
 9   Année                   176600 non-null  int64  
 10  Unité                   176600 non-null  object 
 11  Valeur                  176600 non-null  float64
 12  Symbole                 176600 non-null  object 
 13  Description du Symbole  176600 non-null  object 
dtypes: float64(1), int64

In [12]:
#Afficher les 5 premières lignes de la table
df_dispo_alimentaire_2017.head()

Code Domaine                      Domaine  Code zone         Zone  \
0          FBS  Nouveaux Bilans Alimentaire          2  Afghanistan   
1          FBS  Nouveaux Bilans Alimentaire          2  Afghanistan   
2          FBS  Nouveaux Bilans Alimentaire          2  Afghanistan   
3          FBS  Nouveaux Bilans Alimentaire          2  Afghanistan   
4          FBS  Nouveaux Bilans Alimentaire          2  Afghanistan   

   Code Élément                   Élément  Code Produit          Produit  \
0          5511                Production          2511  Blé et produits   
1          5611   Importations - Quantité          2511  Blé et produits   
2          5072        Variation de stock          2511  Blé et produits   
3          5911   Exportations - Quantité          2511  Blé et produits   
4          5301  Disponibilité intérieure          2511  Blé et produits   

   Code année  Année               Unité  Valeur Symbole  \
0        2017   2017  Milliers de tonnes  4281.0       S   
1        2017   2017  Milliers de tonnes  2302.0       S   
2        2017   2017  Milliers de tonnes  -119.0       S   
3        2017   2017  Milliers de tonnes     0.0       S   
4        2017   2017  Milliers de tonnes  6701.0       S   

  Description du Symbole  
0  Données standardisées  
1  Données standardisées  
2  Données standardisées  
3  Données standardisées  
4  Données standardisées

#### **SELECTION DES COLONNES ET DES LIGNES PERTINENTES**

In [14]:
#Selection de la valeur Viande de Volailles dans la colonne produit
df_dispo_alimentaire_volailles = df_dispo_alimentaire_2017[df_dispo_alimentaire_2017["Produit"] == "Viande de Volailles"]

In [15]:
df_dispo_alimentaire_volailles.head()

Code Domaine                      Domaine  Code zone         Zone  \
651          FBS  Nouveaux Bilans Alimentaire          2  Afghanistan   
652          FBS  Nouveaux Bilans Alimentaire          2  Afghanistan   
653          FBS  Nouveaux Bilans Alimentaire          2  Afghanistan   
654          FBS  Nouveaux Bilans Alimentaire          2  Afghanistan   
655          FBS  Nouveaux Bilans Alimentaire          2  Afghanistan   

     Code Élément                   Élément  Code Produit  \
651          5511                Production          2734   
652          5611   Importations - Quantité          2734   
653          5072        Variation de stock          2734   
654          5301  Disponibilité intérieure          2734   
655          5123                    Pertes          2734   

                 Produit  Code année  Année               Unité  Valeur  \
651  Viande de Volailles        2017   2017  Milliers de tonnes    28.0   
652  Viande de Volailles        2017   2017  Milliers de tonnes    29.0   
653  Viande de Volailles        2017   2017  Milliers de tonnes     0.0   
654  Viande de Volailles        2017   2017  Milliers de tonnes    57.0   
655  Viande de Volailles        2017   2017  Milliers de tonnes     2.0   

    Symbole Description du Symbole  
651       S  Données standardisées  
652       S  Données standardisées  
653       S  Données standardisées  
654       S  Données standardisées  
655       S  Données standardisées

In [16]:
#Suppression de colonnes non utiles
df_dispo_alimentaire_volailles = df_dispo_alimentaire_volailles.copy()
df_dispo_alimentaire_volailles.drop(columns=["Code zone","Code Domaine", "Domaine", "Code Élément", "Code année", "Code Produit", "Description du Symbole"], inplace=True)

In [17]:
df_dispo_alimentaire_volailles.head()

Zone                   Élément              Produit  Année  \
651  Afghanistan                Production  Viande de Volailles   2017   
652  Afghanistan   Importations - Quantité  Viande de Volailles   2017   
653  Afghanistan        Variation de stock  Viande de Volailles   2017   
654  Afghanistan  Disponibilité intérieure  Viande de Volailles   2017   
655  Afghanistan                    Pertes  Viande de Volailles   2017   

                  Unité  Valeur Symbole  
651  Milliers de tonnes    28.0       S  
652  Milliers de tonnes    29.0       S  
653  Milliers de tonnes     0.0       S  
654  Milliers de tonnes    57.0       S  
655  Milliers de tonnes     2.0       S

#### **MODIFICATION DE LA STRUCTURE DU DATAFRAME df_volailles**

In [19]:
#Réalisation d'un pivot pour passer certaines lignes en colonnes
df_volailles = df_dispo_alimentaire_volailles.pivot(index='Zone', columns='Élément', values='Valeur').reset_index()

In [20]:
df_volailles.head()

Élément            Zone  Alimentation pour touristes  Aliments pour animaux  \
0           Afghanistan                          NaN                    NaN   
1        Afrique du Sud                          0.0                    NaN   
2               Albanie                          NaN                    NaN   
3               Algérie                          0.0                    NaN   
4             Allemagne                          NaN                    NaN   

Élément  Autres utilisations (non alimentaire)  \
0                                          NaN   
1                                          NaN   
2                                          NaN   
3                                          NaN   
4                                          NaN   

Élément  Disponibilité alimentaire (Kcal/personne/jour)  \
0                                                   5.0   
1                                                 143.0   
2                                                  85.0   
3                                                  22.0   
4                                                  71.0   

Élément  Disponibilité alimentaire en quantité (kg/personne/an)  \
0                                                     1.53        
1                                                    35.69        
2                                                    16.36        
3                                                     6.38        
4                                                    19.47        

Élément  Disponibilité de matière grasse en quantité (g/personne/jour)  \
0                                                     0.33               
1                                                     9.25               
2                                                     6.45               
3                                                     1.50               
4                                                     4.16               

Élément  Disponibilité de protéines en quantité (g/personne/jour)  \
0                                                     0.54          
1                                                    14.11          
2                                                     6.26          
3                                                     1.97          
4                                                     7.96          

Élément  Disponibilité intérieure  Exportations - Quantité  \
0                            57.0                      NaN   
1                          2118.0                     63.0   
2                            47.0                      0.0   
3                           277.0                      0.0   
4                          1739.0                    646.0   

Élément  Importations - Quantité  Nourriture  Pertes  Production  Résidus  \
0                           29.0        55.0     2.0        28.0      0.0   
1                          514.0      2035.0    83.0      1667.0      0.0   
2                           38.0        47.0     NaN        13.0      0.0   
3                            2.0       264.0    13.0       275.0      0.0   
4                          842.0      1609.0     NaN      1514.0    -38.0   

Élément  Semences  Traitement  Variation de stock  
0             NaN         NaN                 0.0  
1             NaN         NaN                -0.0  
2             NaN         NaN                 4.0  
3             NaN         NaN                 0.0  
4             NaN       167.0               -29.0

In [21]:
#Caractéristiques de df_volailles
df_volailles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172 entries, 0 to 171
Data columns (total 18 columns):
 #   Column                                                         Non-Null Count  Dtype  
---  ------                                                         --------------  -----  
 0   Zone                                                           172 non-null    object 
 1   Alimentation pour touristes                                    78 non-null     float64
 2   Aliments pour animaux                                          1 non-null      float64
 3   Autres utilisations (non alimentaire)                          34 non-null     float64
 4   Disponibilité alimentaire (Kcal/personne/jour)                 172 non-null    float64
 5   Disponibilité alimentaire en quantité (kg/personne/an)         172 non-null    float64
 6   Disponibilité de matière grasse en quantité (g/personne/jour)  172 non-null    float64
 7   Disponibilité de protéines en quantité (g/personne/jour)      

In [22]:
#Suppression de colonnes non utiles
df_volailles.drop(columns=["Alimentation pour touristes","Aliments pour animaux", "Autres utilisations (non alimentaire)", "Disponibilité alimentaire (Kcal/personne/jour)", "Exportations - Quantité", "Disponibilité intérieure", "Disponibilité de matière grasse en quantité (g/personne/jour)", "Disponibilité de protéines en quantité (g/personne/jour)", "Pertes", "Résidus", "Nourriture", "Semences", "Traitement", "Variation de stock"], inplace=True)

In [23]:
df_volailles.head()

Élément            Zone  \
0           Afghanistan   
1        Afrique du Sud   
2               Albanie   
3               Algérie   
4             Allemagne   

Élément  Disponibilité alimentaire en quantité (kg/personne/an)  \
0                                                     1.53        
1                                                    35.69        
2                                                    16.36        
3                                                     6.38        
4                                                    19.47        

Élément  Importations - Quantité  Production  
0                           29.0        28.0  
1                          514.0      1667.0  
2                           38.0        13.0  
3                            2.0       275.0  
4                          842.0      1514.0

In [24]:
df_volailles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172 entries, 0 to 171
Data columns (total 4 columns):
 #   Column                                                  Non-Null Count  Dtype  
---  ------                                                  --------------  -----  
 0   Zone                                                    172 non-null    object 
 1   Disponibilité alimentaire en quantité (kg/personne/an)  172 non-null    float64
 2   Importations - Quantité                                 170 non-null    float64
 3   Production                                              168 non-null    float64
dtypes: float64(3), object(1)
memory usage: 5.5+ KB


In [25]:
#Identification des lignes comportant des valeurs NaN
lignes_nan = df_volailles[df_volailles.isna().any(axis=1)]
lignes_nan

Élément                                   Zone  \
43                                    Djibouti   
92                                    Maldives   
113                                Ouzbékistan   
130      République démocratique populaire lao   

Élément  Disponibilité alimentaire en quantité (kg/personne/an)  \
43                                                    2.68        
92                                                   13.50        
113                                                   1.96        
130                                                  10.91        

Élément  Importations - Quantité  Production  
43                           3.0         NaN  
92                          12.0         NaN  
113                          NaN         NaN  
130                          NaN         NaN

In [26]:
#Suppression des lignes où toutes les valeurs sont manquantes
df_volailles = df_volailles.dropna()

In [27]:
df_volailles.info()

<class 'pandas.core.frame.DataFrame'>
Index: 168 entries, 0 to 171
Data columns (total 4 columns):
 #   Column                                                  Non-Null Count  Dtype  
---  ------                                                  --------------  -----  
 0   Zone                                                    168 non-null    object 
 1   Disponibilité alimentaire en quantité (kg/personne/an)  168 non-null    float64
 2   Importations - Quantité                                 168 non-null    float64
 3   Production                                              168 non-null    float64
dtypes: float64(3), object(1)
memory usage: 6.6+ KB


**Le dataframe df_volailles ne comporte plus que 5 colonnes et 168 lignes.**

**Par ailleurs aucune donnée n'est manquante.**

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">2.2 - Analyse exploratoire du dataframe df_population</h3>
</div>

In [30]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(df_population.shape[0]))
print("Le tableau comporte {} colonne(s)".format(df_population.shape[1]))

Le tableau comporte 4411 observation(s) ou article(s)
Le tableau comporte 15 colonne(s)


In [31]:
df_population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4411 entries, 0 to 4410
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Code Domaine            4411 non-null   object 
 1   Domaine                 4411 non-null   object 
 2   Code zone               4411 non-null   int64  
 3   Zone                    4411 non-null   object 
 4   Code Élément            4411 non-null   int64  
 5   Élément                 4411 non-null   object 
 6   Code Produit            4411 non-null   int64  
 7   Produit                 4411 non-null   object 
 8   Code année              4411 non-null   int64  
 9   Année                   4411 non-null   int64  
 10  Unité                   4411 non-null   object 
 11  Valeur                  4411 non-null   float64
 12  Symbole                 4411 non-null   object 
 13  Description du Symbole  4411 non-null   object 
 14  Note                    258 non-null    

#### **SELECTION DES COLONNES ET DES LIGNES PERTINENTES**

In [33]:
df_population.head()

Code Domaine                       Domaine  Code zone         Zone  \
0           OA  Séries temporelles annuelles          2  Afghanistan   
1           OA  Séries temporelles annuelles          2  Afghanistan   
2           OA  Séries temporelles annuelles          2  Afghanistan   
3           OA  Séries temporelles annuelles          2  Afghanistan   
4           OA  Séries temporelles annuelles          2  Afghanistan   

   Code Élément            Élément  Code Produit                 Produit  \
0           511  Population totale          3010  Population-Estimations   
1           511  Population totale          3010  Population-Estimations   
2           511  Population totale          3010  Population-Estimations   
3           511  Population totale          3010  Population-Estimations   
4           511  Population totale          3010  Population-Estimations   

   Code année  Année           Unité     Valeur Symbole  \
0        2000   2000  1000 personnes  20779.953       X   
1        2001   2001  1000 personnes  21606.988       X   
2        2002   2002  1000 personnes  22600.770       X   
3        2003   2003  1000 personnes  23680.871       X   
4        2004   2004  1000 personnes  24726.684       X   

          Description du Symbole Note  
0  Sources internationales sûres  NaN  
1  Sources internationales sûres  NaN  
2  Sources internationales sûres  NaN  
3  Sources internationales sûres  NaN  
4  Sources internationales sûres  NaN

In [34]:
#Sélection de l'année 2017
df_population_2017 = df_population[df_population['Année'] == 2017]

In [35]:
df_population_2017.head()

Code Domaine                       Domaine  Code zone            Zone  \
17           OA  Séries temporelles annuelles          2     Afghanistan   
36           OA  Séries temporelles annuelles        202  Afrique du Sud   
55           OA  Séries temporelles annuelles          3         Albanie   
74           OA  Séries temporelles annuelles          4         Algérie   
93           OA  Séries temporelles annuelles         79       Allemagne   

    Code Élément            Élément  Code Produit                 Produit  \
17           511  Population totale          3010  Population-Estimations   
36           511  Population totale          3010  Population-Estimations   
55           511  Population totale          3010  Population-Estimations   
74           511  Population totale          3010  Population-Estimations   
93           511  Population totale          3010  Population-Estimations   

    Code année  Année           Unité     Valeur Symbole  \
17        2017   2017  1000 personnes  36296.113       X   
36        2017   2017  1000 personnes  57009.756       X   
55        2017   2017  1000 personnes   2884.169       X   
74        2017   2017  1000 personnes  41389.189       X   
93        2017   2017  1000 personnes  82658.409       X   

           Description du Symbole Note  
17  Sources internationales sûres  NaN  
36  Sources internationales sûres  NaN  
55  Sources internationales sûres  NaN  
74  Sources internationales sûres  NaN  
93  Sources internationales sûres  NaN

In [36]:
#Suppression de colonnes non essentielles
df_population_2017 = df_population_2017.copy()
df_population_2017.drop(['Code Domaine', 'Domaine', 'Code zone','Code Élément', 'Code Produit', 'Code année','Description du Symbole', 'Symbole', 'Note'], axis=1, inplace=True)

In [37]:
df_population_2017.head()

Zone            Élément                 Produit  Année  \
17     Afghanistan  Population totale  Population-Estimations   2017   
36  Afrique du Sud  Population totale  Population-Estimations   2017   
55         Albanie  Population totale  Population-Estimations   2017   
74         Algérie  Population totale  Population-Estimations   2017   
93       Allemagne  Population totale  Population-Estimations   2017   

             Unité     Valeur  
17  1000 personnes  36296.113  
36  1000 personnes  57009.756  
55  1000 personnes   2884.169  
74  1000 personnes  41389.189  
93  1000 personnes  82658.409

In [38]:
df_population_2017.rename(columns={"Valeur": "Population"}, inplace=True)

In [39]:
df_population_2017.drop(['Élément', 'Produit', 'Unité'], axis=1, inplace=True)

In [40]:
df_population_2017.info()

<class 'pandas.core.frame.DataFrame'>
Index: 236 entries, 17 to 4409
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Zone        236 non-null    object 
 1   Année       236 non-null    int64  
 2   Population  236 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 7.4+ KB


**Le dataframe df_population_2017 ne comporte plus que 3 colonnes et 236 lignes.**

**Par ailleurs aucune donnée n'est manquante.**

#### **Calcul de la population mondiale 2017**

In [43]:
population_mondiale_2017 = round(df_population_2017.Population.sum() *1000)
print("La population mondiale est de", population_mondiale_2017, "habitants en 2017.")

La population mondiale est de 7548134111 habitants en 2017.


<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">2.3 - Analyse exploratoire du dataframe pop_urbaine_2017</h3>
</div>

In [45]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(df_pop_urbaine_2017.shape[0]))
print("Le tableau comporte {} colonne(s)".format(df_pop_urbaine_2017.shape[1]))

Le tableau comporte 217 observation(s) ou article(s)
Le tableau comporte 2 colonne(s)


In [46]:
#Consulter le nombre de colonnes , La nature des données dans chacune des colonnes, et le nombre de valeurs présentes dans chacune des colonnes
df_pop_urbaine_2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 217 entries, 0 to 216
Data columns (total 2 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Zone                       217 non-null    object 
 1   % population urbaine 2017  215 non-null    float64
dtypes: float64(1), object(1)
memory usage: 3.5+ KB


In [47]:
df_pop_urbaine_2017.head()

Zone  % population urbaine 2017
0     Afghanistan                     25.250
1         Albania                     59.383
2         Algeria                     72.052
3  American Samoa                     87.170
4         Andorra                     88.150

In [48]:
#Identification des lignes comportant des valeurs NaN
lignes_nan_pop_urb = df_pop_urbaine_2017[df_pop_urbaine_2017.isna().any(axis=1)]
lignes_nan_pop_urb

Zone  % population urbaine 2017
105                    Kosovo                        NaN
183  St. Martin (French part)                        NaN

In [49]:
#Suppression des lignes comportant des valeurs manquantes
df_pop_urbaine_2017 = df_pop_urbaine_2017.dropna()

In [50]:
df_pop_urbaine_2017.info()

<class 'pandas.core.frame.DataFrame'>
Index: 215 entries, 0 to 216
Data columns (total 2 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Zone                       215 non-null    object 
 1   % population urbaine 2017  215 non-null    float64
dtypes: float64(1), object(1)
memory usage: 5.0+ KB


**Le dataframe df_pop_urbaine_2017 ne comporte plus que 2 colonnes et 215 lignes.**

**Par ailleurs aucune donnée n'est manquante.**

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">2.4 - Analyse exploratoire du dataframe croissance_pib_2017</h3>
</div>

In [53]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(df_croissance_pib_2017.shape[0]))
print("Le tableau comporte {} colonne(s)".format(df_croissance_pib_2017.shape[1]))

Le tableau comporte 217 observation(s) ou article(s)
Le tableau comporte 2 colonne(s)


In [54]:
#Consulter le nombre de colonnes , La nature des données dans chacune des colonnes, et le nombre de valeurs présentes dans chacune des colonnes
df_croissance_pib_2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 217 entries, 0 to 216
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Zone                 217 non-null    object
 1   Croissance PIB 2017  217 non-null    object
dtypes: object(2)
memory usage: 3.5+ KB


In [55]:
#Convertir les valeurs de la colonne Croissance PIB 2017 au format numérique
df_croissance_pib_2017["Croissance PIB 2017"] = pd.to_numeric(df_croissance_pib_2017["Croissance PIB 2017"], errors='coerce')

In [56]:
df_croissance_pib_2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 217 entries, 0 to 216
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Zone                 217 non-null    object 
 1   Croissance PIB 2017  209 non-null    float64
dtypes: float64(1), object(1)
memory usage: 3.5+ KB


In [57]:
#Identification des lignes comportant des valeurs manquantes
lignes_nan_croissancepib = df_croissance_pib_2017[df_croissance_pib_2017.isna().any(axis=1)]
lignes_nan_croissancepib

Zone  Croissance PIB 2017
27      British Virgin Islands                  NaN
61                     Eritrea                  NaN
75                   Gibraltar                  NaN
103  Korea, Dem. People's Rep.                  NaN
114              Liechtenstein                  NaN
140              New Caledonia                  NaN
178                South Sudan                  NaN
210              Venezuela, RB                  NaN

In [58]:
#Suppression des lignes comportant des valeurs manquantes
df_croissance_pib_2017 = df_croissance_pib_2017.dropna()

In [59]:
df_croissance_pib_2017.info()

<class 'pandas.core.frame.DataFrame'>
Index: 209 entries, 0 to 216
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Zone                 209 non-null    object 
 1   Croissance PIB 2017  209 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.9+ KB


**Le dataframe df_croissance_pib_2017 ne comporte plus que 2 colonnes et 209 lignes.**

**Par ailleurs aucune donnée n'est manquante.**

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">2.5 - Analyse exploratoire du dataframe doing_business_2017</h3>
</div>

In [62]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(df_doing_business_2017.shape[0]))
print("Le tableau comporte {} colonne(s)".format(df_doing_business_2017.shape[1]))

Le tableau comporte 191 observation(s) ou article(s)
Le tableau comporte 2 colonne(s)


In [63]:
#Consulter le nombre de colonnes , La nature des données dans chacune des colonnes, et le nombre de valeurs présentes dans chacune des colonnes
df_doing_business_2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191 entries, 0 to 190
Data columns (total 2 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   Zone                       191 non-null    object
 1   Doing business score 2017  191 non-null    object
dtypes: object(2)
memory usage: 3.1+ KB


In [64]:
#Convertir les valeurs de la colonne Croissance PIB 2017 au format numérique
df_doing_business_2017["Doing business score 2017"] = pd.to_numeric(df_doing_business_2017["Doing business score 2017"], errors='coerce')

In [65]:
df_doing_business_2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191 entries, 0 to 190
Data columns (total 2 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Zone                       191 non-null    object 
 1   Doing business score 2017  190 non-null    float64
dtypes: float64(1), object(1)
memory usage: 3.1+ KB


In [66]:
df_doing_business_2017.head()

Zone  Doing business score 2017
0          Afghanistan                   37.13062
1              Albania                   66.83770
2              Algeria                   46.22686
3               Angola                   39.00774
4  Antigua and Barbuda                   59.79669

In [67]:
#Identification des lignes comportant des valeurs manquantes
lignes_nan_db2017 = df_doing_business_2017[df_doing_business_2017.isna().any(axis=1)]
lignes_nan_db2017

Zone  Doing business score 2017
98  Liechtenstein                        NaN

In [68]:
#Suppression des lignes comportant des valeurs manquantes
df_doing_business_2017 = df_doing_business_2017.dropna()

In [69]:
df_doing_business_2017.info()

<class 'pandas.core.frame.DataFrame'>
Index: 190 entries, 0 to 190
Data columns (total 2 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Zone                       190 non-null    object 
 1   Doing business score 2017  190 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.5+ KB


**Le dataframe df_doing_business_2017 ne comporte plus que 2 colonnes et 190 lignes.**

**Par ailleurs aucune donnée n'est manquante.**

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">2.6 - Analyse exploratoire du dataframe idh_2017</h3>
</div>

In [72]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(df_idh_2017.shape[0]))
print("Le tableau comporte {} colonne(s)".format(df_idh_2017.shape[1]))

Le tableau comporte 192 observation(s) ou article(s)
Le tableau comporte 2 colonne(s)


In [73]:
#Consulter le nombre de colonnes , La nature des données dans chacune des colonnes, et le nombre de valeurs présentes dans chacune des colonnes
df_idh_2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192 entries, 0 to 191
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Zone      192 non-null    object 
 1   Idh 2017  192 non-null    float64
dtypes: float64(1), object(1)
memory usage: 3.1+ KB


In [74]:
df_idh_2017.head()

Zone  Idh 2017
0           Afghanistan     0.496
1                Angola     0.610
2               Albania     0.798
3               Andorra     0.873
4  United Arab Emirates     0.884

**Le dataframe idh_2017 n'a pas été modifié et aucune donnée ne sont manquantes .**


<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">2.7 - Analyse exploratoire du dataframe pib_hbt_2017</h3>
</div>

In [77]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(df_pib_hbt_2017.shape[0]))
print("Le tableau comporte {} colonne(s)".format(df_pib_hbt_2017.shape[1]))

Le tableau comporte 217 observation(s) ou article(s)
Le tableau comporte 2 colonne(s)


In [78]:
#Consulter le nombre de colonnes , La nature des données dans chacune des colonnes, et le nombre de valeurs présentes dans chacune des colonnes
df_pib_hbt_2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 217 entries, 0 to 216
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Zone            217 non-null    object
 1   PIB / hbt 2017  217 non-null    object
dtypes: object(2)
memory usage: 3.5+ KB


In [79]:
df_pib_hbt_2017.head()

Zone    PIB / hbt 2017
0     Afghanistan  562.769574140988
1         Albania  4283.98262744437
2         Algeria  4742.90075532529
3  American Samoa  11930.7771236826
4         Andorra  39361.0622634329

In [80]:
#Convertir les valeurs de la colonne Croissance PIB 2017 au format numérique
df_pib_hbt_2017["PIB / hbt 2017"] = pd.to_numeric(df_pib_hbt_2017["PIB / hbt 2017"], errors='coerce')

In [81]:
df_pib_hbt_2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 217 entries, 0 to 216
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Zone            217 non-null    object 
 1   PIB / hbt 2017  208 non-null    float64
dtypes: float64(1), object(1)
memory usage: 3.5+ KB


In [82]:
#Identification des lignes comportant des valeurs manquantes
lignes_nan_pbihbt = df_pib_hbt_2017[df_pib_hbt_2017.isna().any(axis=1)]
lignes_nan_pbihbt

Zone  PIB / hbt 2017
27      British Virgin Islands             NaN
61                     Eritrea             NaN
75                   Gibraltar             NaN
103  Korea, Dem. People's Rep.             NaN
114              Liechtenstein             NaN
140              New Caledonia             NaN
178                South Sudan             NaN
183   St. Martin (French part)             NaN
210              Venezuela, RB             NaN

In [83]:
#Suppression des lignes comportant des valeurs manquantes
df_pib_hbt_2017 = df_pib_hbt_2017.dropna()

In [84]:
df_pib_hbt_2017.info()

<class 'pandas.core.frame.DataFrame'>
Index: 208 entries, 0 to 216
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Zone            208 non-null    object 
 1   PIB / hbt 2017  208 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.9+ KB


**Le dataframe df_pib_hbt_2017 ne comporte plus que 2 colonnes et 208 lignes.**

**Par ailleurs aucune donnée n'est manquante.**

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">2.8 - Analyse exploratoire du dataframe stabilité_politique_2017</h3>
</div>

In [87]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(df_stabilité_politique_2017.shape[0]))
print("Le tableau comporte {} colonne(s)".format(df_stabilité_politique_2017.shape[1]))

Le tableau comporte 214 observation(s) ou article(s)
Le tableau comporte 2 colonne(s)


In [88]:
#Consulter le nombre de colonnes , La nature des données dans chacune des colonnes, et le nombre de valeurs présentes dans chacune des colonnes
df_stabilité_politique_2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 2 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Zone                      214 non-null    object
 1   Stabilité Politique 2017  214 non-null    object
dtypes: object(2)
memory usage: 3.5+ KB


In [89]:
df_stabilité_politique_2017.head()

Zone Stabilité Politique 2017
0     Afghanistan         -2.7949755191803
1         Albania        0.373770743608475
2         Algeria       -0.919614315032959
3  American Samoa         1.18432366847992
4         Andorra         1.39288973808289

In [90]:
#Convertir les valeurs de la colonne Croissance PIB 2017 au format numérique
df_stabilité_politique_2017["Stabilité Politique 2017"] = pd.to_numeric(df_stabilité_politique_2017["Stabilité Politique 2017"], errors='coerce')

In [91]:
df_stabilité_politique_2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 2 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Zone                      214 non-null    object 
 1   Stabilité Politique 2017  211 non-null    float64
dtypes: float64(1), object(1)
memory usage: 3.5+ KB


In [92]:
#Identification des lignes comportant des valeurs manquantes
lignes_nan_stapol = df_stabilité_politique_2017[df_stabilité_politique_2017.isna().any(axis=1)]
lignes_nan_stapol

Zone  Stabilité Politique 2017
45           Cook Islands                       NaN
138  Netherlands Antilles                       NaN
143                  Niue                       NaN

In [93]:
#Suppression des lignes comportant des valeurs manquantes
df_stabilité_politique_2017 = df_stabilité_politique_2017.dropna()

In [94]:
df_stabilité_politique_2017.info()

<class 'pandas.core.frame.DataFrame'>
Index: 211 entries, 0 to 213
Data columns (total 2 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Zone                      211 non-null    object 
 1   Stabilité Politique 2017  211 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.9+ KB


**Le dataframe df_stabilité_politique_2017 ne comporte plus que 2 colonnes et 211 lignes.**

**Par ailleurs aucune donnée n'est manquante.**

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">2.9 - Analyse exploratoire du dataframe liaison_zone</h3>
</div>

In [97]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(df_liaison_zone.shape[0]))
print("Le tableau comporte {} colonne(s)".format(df_liaison_zone.shape[1]))

Le tableau comporte 218 observation(s) ou article(s)
Le tableau comporte 2 colonne(s)


In [98]:
#Consulter le nombre de colonnes , La nature des données dans chacune des colonnes, et le nombre de valeurs présentes dans chacune des colonnes
df_liaison_zone.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 218 entries, 0 to 217
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Zone fr  218 non-null    object
 1   Zone en  218 non-null    object
dtypes: object(2)
memory usage: 3.5+ KB


In [99]:
df_liaison_zone.head()

Zone fr         Zone en
0        Afghanistan     Afghanistan
1            Albanie         Albania
2            Algérie         Algeria
3  Samoa américaines  American Samoa
4            Andorre         Andorra

**Le dataframe df_liaison_zone n'a pas été modifié et aucune donnée ne sont manquantes .**

<div style="background-color: RGB(51,165,182);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 3 - Jointure des dataframes</h2>
</div>

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">3.1 - Jointure df_volailles et df_population_2017</h3>
</div>

In [103]:
#Jointure entre les dataframes df_volailles et df_population_2017
df_volailles_pop2017 = pd.merge(df_volailles, df_population_2017, on='Zone', how='outer', indicator=True)

In [104]:
#Vérification des correspondances
df_volailles_pop2017._merge.value_counts()

_merge
both          168
right_only     68
left_only       0
Name: count, dtype: int64

In [105]:
#Identification des données uniquement présent dans df_population_2017
df_right_only_pop = df_volailles_pop2017[df_volailles_pop2017["_merge"] == "right_only"]
df_right_only_pop

Zone  \
5                        Andorre   
7                       Anguilla   
9    Antilles néerlandaises (ex)   
13                         Aruba   
18                       Bahreïn   
..                           ...   
230                Îles Marshall   
232      Îles Turques-et-Caïques   
233     Îles Vierges américaines   
234    Îles Vierges britanniques   
235        Îles Wallis-et-Futuna   

     Disponibilité alimentaire en quantité (kg/personne/an)  \
5                                                  NaN        
7                                                  NaN        
9                                                  NaN        
13                                                 NaN        
18                                                 NaN        
..                                                 ...        
230                                                NaN        
232                                                NaN        
233                                                NaN        
234                                                NaN        
235                                                NaN        

     Importations - Quantité  Production  Année  Population      _merge  
5                        NaN         NaN   2017      77.001  right_only  
7                        NaN         NaN   2017      14.584  right_only  
9                        NaN         NaN   2017     275.186  right_only  
13                       NaN         NaN   2017     105.366  right_only  
18                       NaN         NaN   2017    1494.076  right_only  
..                       ...         ...    ...         ...         ...  
230                      NaN         NaN   2017      58.058  right_only  
232                      NaN         NaN   2017      37.115  right_only  
233                      NaN         NaN   2017     104.751  right_only  
234                      NaN         NaN   2017      29.577  right_only  
235                      NaN         NaN   2017      11.900  right_only  

[68 rows x 7 columns]

In [106]:
#On ne garde que les lignes avec  correspondances
df_volailles_pop2017 = df_volailles_pop2017[df_volailles_pop2017["_merge"] == "both"]

In [107]:
#Informations concernant le nouveau dataframe
df_volailles_pop2017.info()

<class 'pandas.core.frame.DataFrame'>
Index: 168 entries, 0 to 231
Data columns (total 7 columns):
 #   Column                                                  Non-Null Count  Dtype   
---  ------                                                  --------------  -----   
 0   Zone                                                    168 non-null    object  
 1   Disponibilité alimentaire en quantité (kg/personne/an)  168 non-null    float64 
 2   Importations - Quantité                                 168 non-null    float64 
 3   Production                                              168 non-null    float64 
 4   Année                                                   168 non-null    int64   
 5   Population                                              168 non-null    float64 
 6   _merge                                                  168 non-null    category
dtypes: category(1), float64(4), int64(1), object(1)
memory usage: 9.5+ KB


In [108]:
df_volailles_pop2017.head()

Zone  Disponibilité alimentaire en quantité (kg/personne/an)  \
0     Afghanistan                                               1.53        
1  Afrique du Sud                                              35.69        
2         Albanie                                              16.36        
3         Algérie                                               6.38        
4       Allemagne                                              19.47        

   Importations - Quantité  Production  Année  Population _merge  
0                     29.0        28.0   2017   36296.113   both  
1                    514.0      1667.0   2017   57009.756   both  
2                     38.0        13.0   2017    2884.169   both  
3                      2.0       275.0   2017   41389.189   both  
4                    842.0      1514.0   2017   82658.409   both

In [109]:
#Suppression de colonnes non utiles
df_volailles_pop2017.drop(columns=["_merge","Année"], inplace=True)

In [110]:
df_volailles_pop2017.head()

Zone  Disponibilité alimentaire en quantité (kg/personne/an)  \
0     Afghanistan                                               1.53        
1  Afrique du Sud                                              35.69        
2         Albanie                                              16.36        
3         Algérie                                               6.38        
4       Allemagne                                              19.47        

   Importations - Quantité  Production  Population  
0                     29.0        28.0   36296.113  
1                    514.0      1667.0   57009.756  
2                     38.0        13.0    2884.169  
3                      2.0       275.0   41389.189  
4                    842.0      1514.0   82658.409

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">3.2 - Jointure df_volailles_pop2017 et df_liaison_zone</h3>
</div>

In [112]:
#Jointure entre les dataframes df_volailles et df_population_2017
df_volailles_pop2017_liaison = df_volailles_pop2017.merge(df_liaison_zone, left_on='Zone', right_on="Zone fr", how='outer', indicator=True)

In [113]:
#Vérification des correspondances
df_volailles_pop2017_liaison._merge.value_counts()

_merge
both          168
right_only     50
left_only       0
Name: count, dtype: int64

In [114]:
#Identification des données uniquement présent dans df_population_2017
df_right_only_liaison = df_volailles_pop2017_liaison[df_volailles_pop2017_liaison["_merge"] == "right_only"]
df_right_only_liaison

Zone  Disponibilité alimentaire en quantité (kg/personne/an)  \
5    NaN                                                NaN        
11   NaN                                                NaN        
16   NaN                                                NaN        
21   NaN                                                NaN        
22   NaN                                                NaN        
26   NaN                                                NaN        
30   NaN                                                NaN        
44   NaN                                                NaN        
49   NaN                                                NaN        
52   NaN                                                NaN        
65   NaN                                                NaN        
67   NaN                                                NaN        
69   NaN                                                NaN        
72   NaN                                                NaN        
94   NaN                                                NaN        
99   NaN                                                NaN        
101  NaN                                                NaN        
108  NaN                                                NaN        
115  NaN                                                NaN        
116  NaN                                                NaN        
122  NaN                                                NaN        
132  NaN                                                NaN        
134  NaN                                                NaN        
135  NaN                                                NaN        
137  NaN                                                NaN        
143  NaN                                                NaN        
146  NaN                                                NaN        
150  NaN                                                NaN        
155  NaN                                                NaN        
156  NaN                                                NaN        
160  NaN                                                NaN        
161  NaN                                                NaN        
165  NaN                                                NaN        
168  NaN                                                NaN        
170  NaN                                                NaN        
171  NaN                                                NaN        
174  NaN                                                NaN        
176  NaN                                                NaN        
188  NaN                                                NaN        
193  NaN                                                NaN        
205  NaN                                                NaN        
208  NaN                                                NaN        
209  NaN                                                NaN        
210  NaN                                                NaN        
211  NaN                                                NaN        
212  NaN                                                NaN        
213  NaN                                                NaN        
215  NaN                                                NaN        
216  NaN                                                NaN        
217  NaN                                                NaN        

     Importations - Quantité  Production  Population  \
5                        NaN         NaN         NaN   
11                       NaN         NaN         NaN   
16                       NaN         NaN         NaN   
21                       NaN         NaN         NaN   
22                       NaN         NaN         NaN   
26                       NaN         NaN         NaN   
30                       NaN         NaN         NaN   
44                       NaN         NaN         NaN   
49                       NaN   

In [115]:
#On ne garde que les lignes avec  correspondances
df_volailles_pop2017_liaison = df_volailles_pop2017_liaison[df_volailles_pop2017_liaison["_merge"] == "both"]

In [116]:
df_volailles_pop2017_liaison.info()

<class 'pandas.core.frame.DataFrame'>
Index: 168 entries, 0 to 214
Data columns (total 8 columns):
 #   Column                                                  Non-Null Count  Dtype   
---  ------                                                  --------------  -----   
 0   Zone                                                    168 non-null    object  
 1   Disponibilité alimentaire en quantité (kg/personne/an)  168 non-null    float64 
 2   Importations - Quantité                                 168 non-null    float64 
 3   Production                                              168 non-null    float64 
 4   Population                                              168 non-null    float64 
 5   Zone fr                                                 168 non-null    object  
 6   Zone en                                                 168 non-null    object  
 7   _merge                                                  168 non-null    category
dtypes: category(1), float64(4), object(3

In [117]:
#Suppression de colonnes non utiles
df_volailles_pop2017_liaison.drop(columns=["_merge","Zone fr"], inplace=True)

In [118]:
df_volailles_pop2017_liaison

Zone  \
0              Afghanistan   
1           Afrique du Sud   
2                  Albanie   
3                  Algérie   
4                Allemagne   
..                     ...   
203    Émirats arabes unis   
204               Équateur   
206  États-Unis d'Amérique   
207               Éthiopie   
214           Îles Salomon   

     Disponibilité alimentaire en quantité (kg/personne/an)  \
0                                                 1.53        
1                                                35.69        
2                                                16.36        
3                                                 6.38        
4                                                19.47        
..                                                 ...        
203                                              43.47        
204                                              19.31        
206                                              55.68        
207                                               0.13        
214                                               4.45        

     Importations - Quantité  Production  Population               Zone en  
0                       29.0        28.0   36296.113           Afghanistan  
1                      514.0      1667.0   57009.756          South Africa  
2                       38.0        13.0    2884.169               Albania  
3                        2.0       275.0   41389.189               Algeria  
4                      842.0      1514.0   82658.409               Germany  
..                       ...         ...         ...                   ...  
203                    433.0        48.0    9487.203  United Arab Emirates  
204                      0.0       340.0   16785.361               Ecuador  
206                    123.0     21914.0  325084.756         United States  
207                      1.0        14.0  106399.924              Ethiopia  
214                      6.0         0.0     636.039       Solomon Islands  

[168 rows x 6 columns]

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">3.3 - Jointure df_volailles_pop2017_liaison et df_pop_urbaine_2017</h3>
</div>

In [120]:
#Jointure entre les dataframes df_volailles_pop2017 et df_pop_urbaine_2017
df_avec_pop_urb = df_volailles_pop2017_liaison.merge(df_pop_urbaine_2017, left_on='Zone en', right_on="Zone", how='outer', indicator=True)

In [121]:
#Vérification des correspondances
df_avec_pop_urb._merge.value_counts()

_merge
both          167
right_only     48
left_only       1
Name: count, dtype: int64

In [122]:
#Identification des données uniquement dans df_volailles_pop2017_liaison
df_left_only_volailles = df_avec_pop_urb[df_avec_pop_urb["_merge"] == "left_only"]
df_left_only_volailles

Zone_x  \
188  Chine, Taiwan Province de   

     Disponibilité alimentaire en quantité (kg/personne/an)  \
188                                              33.17        

     Importations - Quantité  Production  Population        Zone en Zone_y  \
188                    161.0       652.0   23674.546  Taiwan, China    NaN   

     % population urbaine 2017     _merge  
188                        NaN  left_only

In [123]:
#Identification des données uniquement présentes dans df_pop_urb_2017
df_right_only_pop_urb = df_avec_pop_urb[df_avec_pop_urb["_merge"] == "right_only"]
df_right_only_pop_urb

Zone_x  Disponibilité alimentaire en quantité (kg/personne/an)  \
3      NaN                                                NaN        
4      NaN                                                NaN        
9      NaN                                                NaN        
14     NaN                                                NaN        
21     NaN                                                NaN        
22     NaN                                                NaN        
27     NaN                                                NaN        
28     NaN                                                NaN        
31     NaN                                                NaN        
36     NaN                                                NaN        
39     NaN                                                NaN        
43     NaN                                                NaN        
44     NaN                                                NaN        
50     NaN                                                NaN        
54     NaN                                                NaN        
60     NaN                                                NaN        
61     NaN                                                NaN        
65     NaN                                                NaN        
75     NaN                                                NaN        
77     NaN                                                NaN        
79     NaN                                                NaN        
94     NaN                                                NaN        
107    NaN                                                NaN        
112    NaN                                                NaN        
113    NaN                                                NaN        
120    NaN                                                NaN        
123    NaN                                                NaN        
127    NaN                                                NaN        
129    NaN                                                NaN        
136    NaN                                                NaN        
145    NaN                                                NaN        
149    NaN                                                NaN        
151    NaN                                                NaN        
157    NaN                                                NaN        
158    NaN                                                NaN        
163    NaN                                                NaN        
168    NaN                                                NaN        
170    NaN                                                NaN        
171    NaN                                                NaN        
175    NaN                                                NaN        
177    NaN                                                NaN        
187    NaN                                                NaN        
194    NaN                                                NaN        
199    NaN                                                NaN        
200    NaN                                                NaN        
207    NaN                                                NaN        
211    NaN                                                NaN        
212    NaN                                                NaN        

     Importations - Quantité  Production  Population Zone en  \
3                        NaN         NaN         NaN     NaN   
4                        NaN         NaN         NaN     NaN   
9                        NaN         NaN         NaN     NaN   
14                       NaN         NaN         NaN     NaN   
21                       NaN         NaN         NaN     NaN   
22                       NaN         NaN         NaN     NaN   
27                       NaN         NaN         NaN     NaN   
28                       NaN         NaN         NaN     NaN 

In [124]:
#On ne garde que les lignes avec  correspondances
df_avec_pop_urb = df_avec_pop_urb[df_avec_pop_urb["_merge"] == "both"]

In [125]:
df_avec_pop_urb.info()

<class 'pandas.core.frame.DataFrame'>
Index: 167 entries, 0 to 215
Data columns (total 9 columns):
 #   Column                                                  Non-Null Count  Dtype   
---  ------                                                  --------------  -----   
 0   Zone_x                                                  167 non-null    object  
 1   Disponibilité alimentaire en quantité (kg/personne/an)  167 non-null    float64 
 2   Importations - Quantité                                 167 non-null    float64 
 3   Production                                              167 non-null    float64 
 4   Population                                              167 non-null    float64 
 5   Zone en                                                 167 non-null    object  
 6   Zone_y                                                  167 non-null    object  
 7   % population urbaine 2017                               167 non-null    float64 
 8   _merge                              

In [126]:
df_avec_pop_urb.head()

Zone_x  Disponibilité alimentaire en quantité (kg/personne/an)  \
0         Afghanistan                                               1.53        
1             Albanie                                              16.36        
2             Algérie                                               6.38        
5              Angola                                              10.56        
6  Antigua-et-Barbuda                                              54.10        

   Importations - Quantité  Production  Population              Zone en  \
0                     29.0        28.0   36296.113          Afghanistan   
1                     38.0        13.0    2884.169              Albania   
2                      2.0       275.0   41389.189              Algeria   
5                    277.0        42.0   29816.766               Angola   
6                      7.0         0.0      95.426  Antigua and Barbuda   

                Zone_y  % population urbaine 2017 _merge  
0          Afghanistan                     25.250   both  
1              Albania                     59.383   both  
2              Algeria                     72.052   both  
5               Angola                     64.839   both  
6  Antigua and Barbuda                     24.713   both

In [127]:
#Suppression de colonnes non utiles
df_avec_pop_urb.drop(columns=["_merge","Zone_y"], inplace=True)

In [128]:
df_avec_pop_urb.head()

Zone_x  Disponibilité alimentaire en quantité (kg/personne/an)  \
0         Afghanistan                                               1.53        
1             Albanie                                              16.36        
2             Algérie                                               6.38        
5              Angola                                              10.56        
6  Antigua-et-Barbuda                                              54.10        

   Importations - Quantité  Production  Population              Zone en  \
0                     29.0        28.0   36296.113          Afghanistan   
1                     38.0        13.0    2884.169              Albania   
2                      2.0       275.0   41389.189              Algeria   
5                    277.0        42.0   29816.766               Angola   
6                      7.0         0.0      95.426  Antigua and Barbuda   

   % population urbaine 2017  
0                     25.250  
1                     59.383  
2                     72.052  
5                     64.839  
6                     24.713

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">3.4 - Jointure df_avec_pop_urb et df_croissance_pib_2017</h3>
</div>

In [130]:
#Jointure entre les dataframes df_avec_pop_urb et df_croissance_pib_2017
df_avec_pib_2017 = df_avec_pop_urb.merge(df_croissance_pib_2017, left_on='Zone en', right_on="Zone", how='outer', indicator=True)

In [131]:
#Vérification des correspondances
df_avec_pib_2017._merge.value_counts()

_merge
both          164
right_only     45
left_only       3
Name: count, dtype: int64

In [132]:
#indentification des valeurs sans correspondance présentes uniquement dans df_avec_pop_urb
df_left_only_pib = df_avec_pib_2017[df_avec_pib_2017["_merge"] == "left_only"]
df_left_only_pib

Zone_x  \
100  République populaire démocratique de Corée   
136                          Nouvelle-Calédonie   
205      Venezuela (République bolivarienne du)   

     Disponibilité alimentaire en quantité (kg/personne/an)  \
100                                               1.62        
136                                              38.71        
205                                              20.28        

     Importations - Quantité  Production  Population  \
100                      0.0        43.0   25429.825   
136                      9.0         1.0     277.150   
205                     25.0       600.0   29402.484   

                       Zone en  % population urbaine 2017 Zone  \
100  Korea, Dem. People's Rep.                     61.678  NaN   
136              New Caledonia                     70.256  NaN   
205              Venezuela, RB                     88.183  NaN   

     Croissance PIB 2017     _merge  
100                  NaN  left_only  
136                  NaN  left_only  
205                  NaN  left_only

In [133]:
#indentification des valeurs sans correspondance présentes uniquement dans df_croissance_pib_2017
df_right_only_pib = df_avec_pib_2017[df_avec_pib_2017["_merge"] == "right_only"]
df_right_only_pib

Zone_x  Disponibilité alimentaire en quantité (kg/personne/an)  \
3      NaN                                                NaN        
4      NaN                                                NaN        
9      NaN                                                NaN        
14     NaN                                                NaN        
21     NaN                                                NaN        
22     NaN                                                NaN        
27     NaN                                                NaN        
30     NaN                                                NaN        
35     NaN                                                NaN        
38     NaN                                                NaN        
42     NaN                                                NaN        
43     NaN                                                NaN        
49     NaN                                                NaN        
53     NaN                                                NaN        
59     NaN                                                NaN        
63     NaN                                                NaN        
74     NaN                                                NaN        
76     NaN                                                NaN        
91     NaN                                                NaN        
102    NaN                                                NaN        
105    NaN                                                NaN        
110    NaN                                                NaN        
117    NaN                                                NaN        
120    NaN                                                NaN        
124    NaN                                                NaN        
126    NaN                                                NaN        
133    NaN                                                NaN        
142    NaN                                                NaN        
146    NaN                                                NaN        
148    NaN                                                NaN        
154    NaN                                                NaN        
155    NaN                                                NaN        
160    NaN                                                NaN        
165    NaN                                                NaN        
167    NaN                                                NaN        
168    NaN                                                NaN        
172    NaN                                                NaN        
178    NaN                                                NaN        
184    NaN                                                NaN        
190    NaN                                                NaN        
195    NaN                                                NaN        
196    NaN                                                NaN        
203    NaN                                                NaN        
207    NaN                                                NaN        
208    NaN                                                NaN        

     Importations - Quantité  Production  Population Zone en  \
3                        NaN         NaN         NaN     NaN   
4                        NaN         NaN         NaN     NaN   
9                        NaN         NaN         NaN     NaN   
14                       NaN         NaN         NaN     NaN   
21                       NaN         NaN         NaN     NaN   
22                       NaN         NaN         NaN     NaN   
27                       NaN         NaN         NaN     NaN   
30                       NaN         NaN         NaN     NaN   
35                       NaN         NaN         NaN     NaN   
38                       NaN         NaN         NaN     NaN   
42                       NaN         NaN         NaN     NaN   
43             

In [134]:
#On ne garde que les lignes avec  correspondances
df_avec_pib_2017 = df_avec_pib_2017[df_avec_pib_2017["_merge"] == "both"]

In [135]:
df_avec_pib_2017.info()

<class 'pandas.core.frame.DataFrame'>
Index: 164 entries, 0 to 211
Data columns (total 10 columns):
 #   Column                                                  Non-Null Count  Dtype   
---  ------                                                  --------------  -----   
 0   Zone_x                                                  164 non-null    object  
 1   Disponibilité alimentaire en quantité (kg/personne/an)  164 non-null    float64 
 2   Importations - Quantité                                 164 non-null    float64 
 3   Production                                              164 non-null    float64 
 4   Population                                              164 non-null    float64 
 5   Zone en                                                 164 non-null    object  
 6   % population urbaine 2017                               164 non-null    float64 
 7   Zone                                                    164 non-null    object  
 8   Croissance PIB 2017                

In [136]:
df_avec_pib_2017.head()

Zone_x  Disponibilité alimentaire en quantité (kg/personne/an)  \
0         Afghanistan                                               1.53        
1             Albanie                                              16.36        
2             Algérie                                               6.38        
5              Angola                                              10.56        
6  Antigua-et-Barbuda                                              54.10        

   Importations - Quantité  Production  Population              Zone en  \
0                     29.0        28.0   36296.113          Afghanistan   
1                     38.0        13.0    2884.169              Albania   
2                      2.0       275.0   41389.189              Algeria   
5                    277.0        42.0   29816.766               Angola   
6                      7.0         0.0      95.426  Antigua and Barbuda   

   % population urbaine 2017                 Zone  Croissance PIB 2017 _merge  
0                     25.250          Afghanistan             2.647003   both  
1                     59.383              Albania             3.283176   both  
2                     72.052              Algeria             1.500000   both  
5                     64.839               Angola            -0.147213   both  
6                     24.713  Antigua and Barbuda             2.712727   both

In [137]:
#Suppression de colonnes non utiles
df_avec_pib_2017.drop(columns=["_merge","Zone"], inplace=True)

In [138]:
df_avec_pib_2017.head()

Zone_x  Disponibilité alimentaire en quantité (kg/personne/an)  \
0         Afghanistan                                               1.53        
1             Albanie                                              16.36        
2             Algérie                                               6.38        
5              Angola                                              10.56        
6  Antigua-et-Barbuda                                              54.10        

   Importations - Quantité  Production  Population              Zone en  \
0                     29.0        28.0   36296.113          Afghanistan   
1                     38.0        13.0    2884.169              Albania   
2                      2.0       275.0   41389.189              Algeria   
5                    277.0        42.0   29816.766               Angola   
6                      7.0         0.0      95.426  Antigua and Barbuda   

   % population urbaine 2017  Croissance PIB 2017  
0                     25.250             2.647003  
1                     59.383             3.283176  
2                     72.052             1.500000  
5                     64.839            -0.147213  
6                     24.713             2.712727

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">3.5 - Jointure df_avec_pib_2017 et df_pib_hbt_2017</h3>
</div>

In [140]:
#Jointure entre les dataframes df_avec_pib_2017 et df_pib__hbt_2017
df_avec_pib_hbt = df_avec_pib_2017.merge(df_pib_hbt_2017, left_on='Zone en', right_on="Zone", how='outer', indicator=True)

In [141]:
#Vérification des correspondances
df_avec_pib_hbt._merge.value_counts()

_merge
both          164
right_only     44
left_only       0
Name: count, dtype: int64

In [142]:
#identification des valeurs sans correspondance présentes uniquement dans df_croissance_pib_2017
df_right_only_pibhbt = df_avec_pib_hbt[df_avec_pib_hbt["_merge"] == "right_only"]
df_right_only_pibhbt

Zone_x  Disponibilité alimentaire en quantité (kg/personne/an)  \
3      NaN                                                NaN        
4      NaN                                                NaN        
9      NaN                                                NaN        
14     NaN                                                NaN        
21     NaN                                                NaN        
22     NaN                                                NaN        
27     NaN                                                NaN        
30     NaN                                                NaN        
35     NaN                                                NaN        
38     NaN                                                NaN        
42     NaN                                                NaN        
43     NaN                                                NaN        
49     NaN                                                NaN        
53     NaN                                                NaN        
59     NaN                                                NaN        
63     NaN                                                NaN        
74     NaN                                                NaN        
76     NaN                                                NaN        
91     NaN                                                NaN        
101    NaN                                                NaN        
104    NaN                                                NaN        
109    NaN                                                NaN        
116    NaN                                                NaN        
119    NaN                                                NaN        
123    NaN                                                NaN        
125    NaN                                                NaN        
132    NaN                                                NaN        
140    NaN                                                NaN        
144    NaN                                                NaN        
146    NaN                                                NaN        
152    NaN                                                NaN        
153    NaN                                                NaN        
158    NaN                                                NaN        
163    NaN                                                NaN        
165    NaN                                                NaN        
166    NaN                                                NaN        
170    NaN                                                NaN        
181    NaN                                                NaN        
187    NaN                                                NaN        
192    NaN                                                NaN        
193    NaN                                                NaN        
200    NaN                                                NaN        
203    NaN                                                NaN        
204    NaN                                                NaN        

     Importations - Quantité  Production  Population Zone en  \
3                        NaN         NaN         NaN     NaN   
4                        NaN         NaN         NaN     NaN   
9                        NaN         NaN         NaN     NaN   
14                       NaN         NaN         NaN     NaN   
21                       NaN         NaN         NaN     NaN   
22                       NaN         NaN         NaN     NaN   
27                       NaN         NaN         NaN     NaN   
30                       NaN         NaN         NaN     NaN   
35                       NaN         NaN         NaN     NaN   
38                       NaN         NaN         NaN     NaN   
42                       NaN         NaN         NaN     NaN   
43                       NaN         NaN         NaN     NaN   
49                   

In [143]:
#On ne garde que les lignes avec  correspondances
df_avec_pib_hbt = df_avec_pib_hbt[df_avec_pib_hbt["_merge"] == "both"]

In [144]:
df_avec_pib_hbt.info()

<class 'pandas.core.frame.DataFrame'>
Index: 164 entries, 0 to 207
Data columns (total 11 columns):
 #   Column                                                  Non-Null Count  Dtype   
---  ------                                                  --------------  -----   
 0   Zone_x                                                  164 non-null    object  
 1   Disponibilité alimentaire en quantité (kg/personne/an)  164 non-null    float64 
 2   Importations - Quantité                                 164 non-null    float64 
 3   Production                                              164 non-null    float64 
 4   Population                                              164 non-null    float64 
 5   Zone en                                                 164 non-null    object  
 6   % population urbaine 2017                               164 non-null    float64 
 7   Croissance PIB 2017                                     164 non-null    float64 
 8   Zone                               

In [145]:
df_avec_pib_hbt.head()

Zone_x  Disponibilité alimentaire en quantité (kg/personne/an)  \
0         Afghanistan                                               1.53        
1             Albanie                                              16.36        
2             Algérie                                               6.38        
5              Angola                                              10.56        
6  Antigua-et-Barbuda                                              54.10        

   Importations - Quantité  Production  Population              Zone en  \
0                     29.0        28.0   36296.113          Afghanistan   
1                     38.0        13.0    2884.169              Albania   
2                      2.0       275.0   41389.189              Algeria   
5                    277.0        42.0   29816.766               Angola   
6                      7.0         0.0      95.426  Antigua and Barbuda   

   % population urbaine 2017  Croissance PIB 2017                 Zone  \
0                     25.250             2.647003          Afghanistan   
1                     59.383             3.283176              Albania   
2                     72.052             1.500000              Algeria   
5                     64.839            -0.147213               Angola   
6                     24.713             2.712727  Antigua and Barbuda   

   PIB / hbt 2017 _merge  
0      562.769574   both  
1     4283.982627   both  
2     4742.900755   both  
5     2911.600842   both  
6    16992.932750   both

In [146]:
#Suppression de colonnes non utiles
df_avec_pib_hbt.drop(columns=["_merge","Zone"], inplace=True)

In [147]:
df_avec_pib_hbt

Zone_x  \
0           Afghanistan   
1               Albanie   
2               Algérie   
5                Angola   
6    Antigua-et-Barbuda   
..                  ...   
201             Vanuatu   
202            Viet Nam   
205               Yémen   
206              Zambie   
207            Zimbabwe   

     Disponibilité alimentaire en quantité (kg/personne/an)  \
0                                                 1.53        
1                                                16.36        
2                                                 6.38        
5                                                10.56        
6                                                54.10        
..                                                 ...        
201                                              11.66        
202                                              12.33        
205                                               8.53        
206                                               3.42        
207                                               4.68        

     Importations - Quantité  Production  Population              Zone en  \
0                       29.0        28.0   36296.113          Afghanistan   
1                       38.0        13.0    2884.169              Albania   
2                        2.0       275.0   41389.189              Algeria   
5                      277.0        42.0   29816.766               Angola   
6                        7.0         0.0      95.426  Antigua and Barbuda   
..                       ...         ...         ...                  ...   
201                      4.0         1.0     285.510              Vanuatu   
202                    291.0       918.0   94600.648             Viet Nam   
205                     78.0       168.0   27834.819          Yemen, Rep.   
206                     12.0        49.0   16853.599               Zambia   
207                      6.0        69.0   14236.595             Zimbabwe   

     % population urbaine 2017  Croissance PIB 2017  PIB / hbt 2017  
0                       25.250             2.647003      562.769574  
1                       59.383             3.283176     4283.982627  
2                       72.052             1.500000     4742.900755  
5                       64.839            -0.147213     2911.600842  
6                       24.713             2.712727    16992.932750  
..                         ...                  ...             ...  
201                     25.163             4.412666     2946.961862  
202                     35.213             6.940190     2868.136800  
205                     36.016            -5.071796     1103.456349  
206                     42.976             3.525863     1308.768292  
207                     32.237             4.734411     1422.193460  

[164 rows x 9 columns]

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">3.6 - Jointure df_avec_pib_hbt et df_doing_business_2017</h3>
</div>

In [149]:
#Jointure entre les dataframes df_avec_pib__hbt et df_doing_business_2017
df_avec_db_2017 = df_avec_pib_hbt.merge(df_doing_business_2017, left_on='Zone en', right_on="Zone", how='outer', indicator=True)

In [150]:
#Vérification des correspondances
df_avec_db_2017._merge.value_counts()

_merge
both          160
right_only     30
left_only       4
Name: count, dtype: int64

In [151]:
#Identification des valeurs sans correspondance présentes uniquement dans df_avec_pib_hbt_2017
df_left_only_db = df_avec_db_2017[df_avec_db_2017["_merge"] == "left_only"]
df_left_only_db

Zone_x  \
42                   Cuba   
60    Polynésie française   
102  Chine - RAS de Macao   
179          Turkménistan   

     Disponibilité alimentaire en quantité (kg/personne/an)  \
42                                               23.72        
60                                               47.40        
102                                              34.47        
179                                               4.52        

     Importations - Quantité  Production  Population           Zone en  \
42                     312.0        29.0   11339.254              Cuba   
60                      15.0         1.0     276.102  French Polynesia   
102                     23.0         3.0     622.585  Macao SAR, China   
179                      9.0        20.0    5757.667      Turkmenistan   

     % population urbaine 2017  Croissance PIB 2017  PIB / hbt 2017 Zone  \
42                      76.977             1.809792     7927.277693  NaN   
60                      61.784             4.292634    20287.768583  NaN   
102                    100.000             9.860052    75807.892751  NaN   
179                     51.153             6.500000     6222.555906  NaN   

     Doing business score 2017     _merge  
42                         NaN  left_only  
60                         NaN  left_only  
102                        NaN  left_only  
179                        NaN  left_only

In [152]:
#Identification des valeurs sans correspondance présentes uniquement dans df_doing_business_2017
df_right_only_db = df_avec_db_2017[df_avec_db_2017["_merge"] == "right_only"]
df_right_only_db

Zone_x  Disponibilité alimentaire en quantité (kg/personne/an)  \
11     NaN                                                NaN        
18     NaN                                                NaN        
23     NaN                                                NaN        
26     NaN                                                NaN        
36     NaN                                                NaN        
37     NaN                                                NaN        
46     NaN                                                NaN        
52     NaN                                                NaN        
53     NaN                                                NaN        
91     NaN                                                NaN        
94     NaN                                                NaN        
99     NaN                                                NaN        
106    NaN                                                NaN        
109    NaN                                                NaN        
113    NaN                                                NaN        
131    NaN                                                NaN        
133    NaN                                                NaN        
139    NaN                                                NaN        
140    NaN                                                NaN        
145    NaN                                                NaN        
150    NaN                                                NaN        
152    NaN                                                NaN        
156    NaN                                                NaN        
158    NaN                                                NaN        
168    NaN                                                NaN        
169    NaN                                                NaN        
175    NaN                                                NaN        
186    NaN                                                NaN        
188    NaN                                                NaN        
190    NaN                                                NaN        

     Importations - Quantité  Production  Population Zone en  \
11                       NaN         NaN         NaN     NaN   
18                       NaN         NaN         NaN     NaN   
23                       NaN         NaN         NaN     NaN   
26                       NaN         NaN         NaN     NaN   
36                       NaN         NaN         NaN     NaN   
37                       NaN         NaN         NaN     NaN   
46                       NaN         NaN         NaN     NaN   
52                       NaN         NaN         NaN     NaN   
53                       NaN         NaN         NaN     NaN   
91                       NaN         NaN         NaN     NaN   
94                       NaN         NaN         NaN     NaN   
99                       NaN         NaN         NaN     NaN   
106                      NaN         NaN         NaN     NaN   
109                      NaN         NaN         NaN     NaN   
113                      NaN         NaN         NaN     NaN   
131                      NaN         NaN         NaN     NaN   
133                      NaN         NaN         NaN     NaN   
139                      NaN         NaN         NaN     NaN   
140                      NaN         NaN         NaN     NaN   
145                      NaN         NaN         NaN     NaN   
150                      NaN         NaN         NaN     NaN   
152                      NaN         NaN         NaN     NaN   
156                      NaN         NaN         NaN     NaN   
158                      NaN         NaN         NaN     NaN   
168                      NaN         NaN         NaN     NaN   
169                      NaN         NaN         NaN     NaN   
175                      NaN         NaN         NaN     NaN   
186                      NaN         NaN 

In [153]:
#On ne garde que les lignes avec  correspondances
df_avec_db_2017 = df_avec_db_2017[df_avec_db_2017["_merge"] == "both"]

In [154]:
df_avec_db_2017.info()

<class 'pandas.core.frame.DataFrame'>
Index: 160 entries, 0 to 193
Data columns (total 12 columns):
 #   Column                                                  Non-Null Count  Dtype   
---  ------                                                  --------------  -----   
 0   Zone_x                                                  160 non-null    object  
 1   Disponibilité alimentaire en quantité (kg/personne/an)  160 non-null    float64 
 2   Importations - Quantité                                 160 non-null    float64 
 3   Production                                              160 non-null    float64 
 4   Population                                              160 non-null    float64 
 5   Zone en                                                 160 non-null    object  
 6   % population urbaine 2017                               160 non-null    float64 
 7   Croissance PIB 2017                                     160 non-null    float64 
 8   PIB / hbt 2017                     

In [155]:
df_avec_db_2017.head()

Zone_x  Disponibilité alimentaire en quantité (kg/personne/an)  \
0         Afghanistan                                               1.53        
1             Albanie                                              16.36        
2             Algérie                                               6.38        
3              Angola                                              10.56        
4  Antigua-et-Barbuda                                              54.10        

   Importations - Quantité  Production  Population              Zone en  \
0                     29.0        28.0   36296.113          Afghanistan   
1                     38.0        13.0    2884.169              Albania   
2                      2.0       275.0   41389.189              Algeria   
3                    277.0        42.0   29816.766               Angola   
4                      7.0         0.0      95.426  Antigua and Barbuda   

   % population urbaine 2017  Croissance PIB 2017  PIB / hbt 2017  \
0                     25.250             2.647003      562.769574   
1                     59.383             3.283176     4283.982627   
2                     72.052             1.500000     4742.900755   
3                     64.839            -0.147213     2911.600842   
4                     24.713             2.712727    16992.932750   

                  Zone  Doing business score 2017 _merge  
0          Afghanistan                   37.13062   both  
1              Albania                   66.83770   both  
2              Algeria                   46.22686   both  
3               Angola                   39.00774   both  
4  Antigua and Barbuda                   59.79669   both

In [156]:
#Suppression de colonnes non utiles
df_avec_db_2017.drop(columns=["_merge","Zone"], inplace=True)

In [157]:
df_avec_db_2017

Zone_x  \
0           Afghanistan   
1               Albanie   
2               Algérie   
3                Angola   
4    Antigua-et-Barbuda   
..                  ...   
187             Vanuatu   
189            Viet Nam   
191               Yémen   
192              Zambie   
193            Zimbabwe   

     Disponibilité alimentaire en quantité (kg/personne/an)  \
0                                                 1.53        
1                                                16.36        
2                                                 6.38        
3                                                10.56        
4                                                54.10        
..                                                 ...        
187                                              11.66        
189                                              12.33        
191                                               8.53        
192                                               3.42        
193                                               4.68        

     Importations - Quantité  Production  Population              Zone en  \
0                       29.0        28.0   36296.113          Afghanistan   
1                       38.0        13.0    2884.169              Albania   
2                        2.0       275.0   41389.189              Algeria   
3                      277.0        42.0   29816.766               Angola   
4                        7.0         0.0      95.426  Antigua and Barbuda   
..                       ...         ...         ...                  ...   
187                      4.0         1.0     285.510              Vanuatu   
189                    291.0       918.0   94600.648             Viet Nam   
191                     78.0       168.0   27834.819          Yemen, Rep.   
192                     12.0        49.0   16853.599               Zambia   
193                      6.0        69.0   14236.595             Zimbabwe   

     % population urbaine 2017  Croissance PIB 2017  PIB / hbt 2017  \
0                       25.250             2.647003      562.769574   
1                       59.383             3.283176     4283.982627   
2                       72.052             1.500000     4742.900755   
3                       64.839            -0.147213     2911.600842   
4                       24.713             2.712727    16992.932750   
..                         ...                  ...             ...   
187                     25.163             4.412666     2946.961862   
189                     35.213             6.940190     2868.136800   
191                     36.016            -5.071796     1103.456349   
192                     42.976             3.525863     1308.768292   
193                     32.237             4.734411     1422.193460   

     Doing business score 2017  
0                     37.13062  
1                     66.83770  
2                     46.22686  
3                     39.00774  
4                     59.79669  
..                         ...  
187                   60.92111  
189                   66.97960  
191                   31.26677  
192                   64.23311  
193                   48.58986  

[160 rows x 10 columns]

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">3.7 - Jointure entre df_avec_db_2017 et df_idh_2017</h3>
</div>

In [159]:
#Jointure entre les dataframes df_avec_db_2017 et df_idh_2017
df_avec_idh_2017 = df_avec_db_2017.merge(df_idh_2017, left_on='Zone en', right_on="Zone", how='outer', indicator=True)

In [160]:
#Vérification des correspondances
df_avec_idh_2017._merge.value_counts()

_merge
both          160
right_only     32
left_only       0
Name: count, dtype: int64

In [161]:
#Identification des valeurs sans correspondance présentes uniquement dans df_idh_2017
df_right_only_idh = df_avec_idh_2017[df_avec_idh_2017["_merge"] == "right_only"]
df_right_only_idh

Zone_x  Disponibilité alimentaire en quantité (kg/personne/an)  \
3      NaN                                                NaN        
12     NaN                                                NaN        
19     NaN                                                NaN        
24     NaN                                                NaN        
27     NaN                                                NaN        
37     NaN                                                NaN        
38     NaN                                                NaN        
43     NaN                                                NaN        
47     NaN                                                NaN        
53     NaN                                                NaN        
54     NaN                                                NaN        
93     NaN                                                NaN        
98     NaN                                                NaN        
99     NaN                                                NaN        
105    NaN                                                NaN        
108    NaN                                                NaN        
112    NaN                                                NaN        
120    NaN                                                NaN        
131    NaN                                                NaN        
132    NaN                                                NaN        
134    NaN                                                NaN        
140    NaN                                                NaN        
145    NaN                                                NaN        
150    NaN                                                NaN        
152    NaN                                                NaN        
157    NaN                                                NaN        
167    NaN                                                NaN        
173    NaN                                                NaN        
177    NaN                                                NaN        
178    NaN                                                NaN        
185    NaN                                                NaN        
187    NaN                                                NaN        

     Importations - Quantité  Production  Population Zone en  \
3                        NaN         NaN         NaN     NaN   
12                       NaN         NaN         NaN     NaN   
19                       NaN         NaN         NaN     NaN   
24                       NaN         NaN         NaN     NaN   
27                       NaN         NaN         NaN     NaN   
37                       NaN         NaN         NaN     NaN   
38                       NaN         NaN         NaN     NaN   
43                       NaN         NaN         NaN     NaN   
47                       NaN         NaN         NaN     NaN   
53                       NaN         NaN         NaN     NaN   
54                       NaN         NaN         NaN     NaN   
93                       NaN         NaN         NaN     NaN   
98                       NaN         NaN         NaN     NaN   
99                       NaN         NaN         NaN     NaN   
105                      NaN         NaN         NaN     NaN   
108                      NaN         NaN         NaN     NaN   
112                      NaN         NaN         NaN     NaN   
120                      NaN         NaN         NaN     NaN   
131                      NaN         NaN         NaN     NaN   
132                      NaN         NaN         NaN     NaN   
134                      NaN         NaN         NaN     NaN   
140                      NaN         NaN         NaN     NaN   
145                      NaN         NaN         NaN     NaN   
150                      NaN         NaN         NaN     NaN   
152                      NaN         NaN         NaN     NaN   
157                      NaN 

In [162]:
#On ne garde que les lignes avec  correspondances
df_avec_idh_2017 = df_avec_idh_2017[df_avec_idh_2017["_merge"] == "both"]

In [163]:
df_avec_idh_2017.info()

<class 'pandas.core.frame.DataFrame'>
Index: 160 entries, 0 to 191
Data columns (total 13 columns):
 #   Column                                                  Non-Null Count  Dtype   
---  ------                                                  --------------  -----   
 0   Zone_x                                                  160 non-null    object  
 1   Disponibilité alimentaire en quantité (kg/personne/an)  160 non-null    float64 
 2   Importations - Quantité                                 160 non-null    float64 
 3   Production                                              160 non-null    float64 
 4   Population                                              160 non-null    float64 
 5   Zone en                                                 160 non-null    object  
 6   % population urbaine 2017                               160 non-null    float64 
 7   Croissance PIB 2017                                     160 non-null    float64 
 8   PIB / hbt 2017                     

In [164]:
#Suppression de colonnes non utiles
df_avec_idh_2017.drop(columns=["_merge","Zone"], inplace=True)

In [165]:
df_avec_idh_2017.head()

Zone_x  Disponibilité alimentaire en quantité (kg/personne/an)  \
0         Afghanistan                                               1.53        
1             Albanie                                              16.36        
2             Algérie                                               6.38        
4              Angola                                              10.56        
5  Antigua-et-Barbuda                                              54.10        

   Importations - Quantité  Production  Population              Zone en  \
0                     29.0        28.0   36296.113          Afghanistan   
1                     38.0        13.0    2884.169              Albania   
2                      2.0       275.0   41389.189              Algeria   
4                    277.0        42.0   29816.766               Angola   
5                      7.0         0.0      95.426  Antigua and Barbuda   

   % population urbaine 2017  Croissance PIB 2017  PIB / hbt 2017  \
0                     25.250             2.647003      562.769574   
1                     59.383             3.283176     4283.982627   
2                     72.052             1.500000     4742.900755   
4                     64.839            -0.147213     2911.600842   
5                     24.713             2.712727    16992.932750   

   Doing business score 2017  Idh 2017  
0                   37.13062     0.496  
1                   66.83770     0.798  
2                   46.22686     0.746  
4                   39.00774     0.610  
5                   59.79669     0.845

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">3.8 - Jointure entre df_avec_idh_2017 et df_stabilité_politique_2017</h3>
</div>

In [167]:
#Jointure entre les dataframes df_avec_idh_2017 et df_avec_sta_pol_2017
df_avec_sta_pol_2017 = df_avec_idh_2017.merge(df_stabilité_politique_2017, left_on='Zone en', right_on="Zone", how='outer', indicator=True)

In [168]:
#Vérification des correspondances
df_avec_sta_pol_2017._merge.value_counts()

_merge
both          160
right_only     51
left_only       0
Name: count, dtype: int64

In [169]:
#Identification des valeurs sans correspondance présentes uniquement dans df_idh_2017
df_right_only_sta = df_avec_sta_pol_2017[df_avec_sta_pol_2017["_merge"] == "right_only"]
df_right_only_sta

Zone_x  Disponibilité alimentaire en quantité (kg/personne/an)  \
3      NaN                                                NaN        
4      NaN                                                NaN        
6      NaN                                                NaN        
10     NaN                                                NaN        
15     NaN                                                NaN        
22     NaN                                                NaN        
23     NaN                                                NaN        
28     NaN                                                NaN        
31     NaN                                                NaN        
36     NaN                                                NaN        
42     NaN                                                NaN        
43     NaN                                                NaN        
48     NaN                                                NaN        
52     NaN                                                NaN        
58     NaN                                                NaN        
59     NaN                                                NaN        
66     NaN                                                NaN        
73     NaN                                                NaN        
75     NaN                                                NaN        
94     NaN                                                NaN        
99     NaN                                                NaN        
101    NaN                                                NaN        
104    NaN                                                NaN        
109    NaN                                                NaN        
110    NaN                                                NaN        
113    NaN                                                NaN        
117    NaN                                                NaN        
120    NaN                                                NaN        
121    NaN                                                NaN        
125    NaN                                                NaN        
127    NaN                                                NaN        
134    NaN                                                NaN        
145    NaN                                                NaN        
147    NaN                                                NaN        
153    NaN                                                NaN        
154    NaN                                                NaN        
155    NaN                                                NaN        
160    NaN                                                NaN        
165    NaN                                                NaN        
167    NaN                                                NaN        
171    NaN                                                NaN        
173    NaN                                                NaN        
183    NaN                                                NaN        
184    NaN                                                NaN        
190    NaN                                                NaN        
194    NaN                                                NaN        
195    NaN                                                NaN        
202    NaN                                                NaN        
204    NaN                                                NaN        
206    NaN                                                NaN        
207    NaN                                                NaN        

     Importations - Quantité  Production  Population Zone en  \
3                        NaN         NaN         NaN     NaN   
4                        NaN         NaN         NaN     NaN   
6                        NaN         NaN         NaN     NaN   
10                       NaN         NaN         NaN     NaN   
15                       NaN         NaN   

In [170]:
#On ne garde que les lignes avec  correspondances
df_avec_sta_pol_2017 = df_avec_sta_pol_2017[df_avec_sta_pol_2017["_merge"] == "both"]

In [171]:
df_avec_sta_pol_2017.info()

<class 'pandas.core.frame.DataFrame'>
Index: 160 entries, 0 to 210
Data columns (total 14 columns):
 #   Column                                                  Non-Null Count  Dtype   
---  ------                                                  --------------  -----   
 0   Zone_x                                                  160 non-null    object  
 1   Disponibilité alimentaire en quantité (kg/personne/an)  160 non-null    float64 
 2   Importations - Quantité                                 160 non-null    float64 
 3   Production                                              160 non-null    float64 
 4   Population                                              160 non-null    float64 
 5   Zone en                                                 160 non-null    object  
 6   % population urbaine 2017                               160 non-null    float64 
 7   Croissance PIB 2017                                     160 non-null    float64 
 8   PIB / hbt 2017                     

In [172]:
df_avec_sta_pol_2017.rename(columns={"Zone_x": "Pays"}, inplace=True)

In [173]:
#Suppression de colonnes non utiles
df_avec_sta_pol_2017.drop(columns=["_merge","Zone", "Zone en"], inplace=True)

In [174]:
df_avec_sta_pol_2017

Pays  \
0           Afghanistan   
1               Albanie   
2               Algérie   
5                Angola   
7    Antigua-et-Barbuda   
..                  ...   
203             Vanuatu   
205            Viet Nam   
208               Yémen   
209              Zambie   
210            Zimbabwe   

     Disponibilité alimentaire en quantité (kg/personne/an)  \
0                                                 1.53        
1                                                16.36        
2                                                 6.38        
5                                                10.56        
7                                                54.10        
..                                                 ...        
203                                              11.66        
205                                              12.33        
208                                               8.53        
209                                               3.42        
210                                               4.68        

     Importations - Quantité  Production  Population  \
0                       29.0        28.0   36296.113   
1                       38.0        13.0    2884.169   
2                        2.0       275.0   41389.189   
5                      277.0        42.0   29816.766   
7                        7.0         0.0      95.426   
..                       ...         ...         ...   
203                      4.0         1.0     285.510   
205                    291.0       918.0   94600.648   
208                     78.0       168.0   27834.819   
209                     12.0        49.0   16853.599   
210                      6.0        69.0   14236.595   

     % population urbaine 2017  Croissance PIB 2017  PIB / hbt 2017  \
0                       25.250             2.647003      562.769574   
1                       59.383             3.283176     4283.982627   
2                       72.052             1.500000     4742.900755   
5                       64.839            -0.147213     2911.600842   
7                       24.713             2.712727    16992.932750   
..                         ...                  ...             ...   
203                     25.163             4.412666     2946.961862   
205                     35.213             6.940190     2868.136800   
208                     36.016            -5.071796     1103.456349   
209                     42.976             3.525863     1308.768292   
210                     32.237             4.734411     1422.193460   

     Doing business score 2017  Idh 2017  Stabilité Politique 2017  
0                     37.13062     0.496                 -2.794976  
1                     66.83770     0.798                  0.373771  
2                     46.22686     0.746                 -0.919614  
5                     39.00774     0.610                 -0.387895  
7                     59.79669     0.845                  0.732061  
..                         ...       ...                       ...  
203                   60.92111     0.607                  0.676285  
205                   66.97960     0.729                  0.211102  
208                   31.26677     0.459                 -2.934317  
209                   64.23311     0.570                  0.142043  
210                   48.58986     0.575                 -0.710431  

[160 rows x 11 columns]

<div style="background-color: RGB(51,165,182);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 4 - Finalisation du fichier avant analyse</h2>
</div>

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">4.1 - Modification du nom</h3>
</div>

In [177]:
#modification du nom du dataframe
df_liste_pays = df_avec_sta_pol_2017

In [178]:
#On retire la France des données car ce pays n'est pas concerné par l'étude
df_liste_pays = df_liste_pays[df_liste_pays['Pays'] != 'France'].reset_index(drop=True)
df_liste_pays.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 11 columns):
 #   Column                                                  Non-Null Count  Dtype  
---  ------                                                  --------------  -----  
 0   Pays                                                    159 non-null    object 
 1   Disponibilité alimentaire en quantité (kg/personne/an)  159 non-null    float64
 2   Importations - Quantité                                 159 non-null    float64
 3   Production                                              159 non-null    float64
 4   Population                                              159 non-null    float64
 5   % population urbaine 2017                               159 non-null    float64
 6   Croissance PIB 2017                                     159 non-null    float64
 7   PIB / hbt 2017                                          159 non-null    float64
 8   Doing business score 2017               

**Le dataframe final comporte des données sur 159 pays, et aucune donnée n'est manquante.**

In [180]:
#Population concernée par la liste de pays en nomnbre d'habitants
population_totale_liste = (df_liste_pays.Population.sum() *1000)
print("La population des différents pays de la liste s'élèvent à", population_totale_liste, "habitants en 2017.")

La population des différents pays de la liste s'élèvent à 7166806360.0 habitants en 2017.


In [181]:
#Calcul de la part de la population mondiale dans la liste des pays
part_pop_liste = round((population_totale_liste / population_mondiale_2017)*100, 1)
print("La population des pays de la liste représente", part_pop_liste, "% de la population mondiale 2017.")

La population des pays de la liste représente 94.9 % de la population mondiale 2017.


In [182]:
#Extraire le dataframe au format .pkl
df_liste_pays.to_pickle('df_liste_pays.pkl')

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">4.2 - Standardisation des données</h3>
</div>

In [184]:
#Colonnes à standardiser
colonnes_a_standardiser = [
    "Disponibilité alimentaire en quantité (kg/personne/an)", "Importations - Quantité", "Production",
    "Population", "% population urbaine 2017", "Croissance PIB 2017", "PIB / hbt 2017", 
    "Doing business score 2017", "Idh 2017", "Stabilité Politique 2017"
]
#Importation de la classe StandardScaler depuis la librairie scikit-learn 
from sklearn.preprocessing import StandardScaler
# Instanciation du scaler
scaler = StandardScaler()
# Sélection des données numériques
df_num = df_liste_pays[colonnes_a_standardiser]
# Standardisation
scaled_array = scaler.fit_transform(df_num)
# Création du DataFrame standardisé
df_num_scaled = pd.DataFrame(scaled_array, columns=colonnes_a_standardiser, index=df_num.index)
# Fusion dans une copie complète du DataFrame original
df_liste_pays_sd = df_liste_pays.copy()
df_liste_pays_sd[colonnes_a_standardiser] = df_num_scaled

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">4.3 - Sauvergarde du fichier</h3>
</div>

In [186]:
#Extraire les dataframe au format .pkl
df_liste_pays_sd.to_pickle('df_liste_pays_sd.pkl')
#Extraire le dataframe au format .pkl
df_liste_pays.to_pickle('df_liste_pays.pkl')